export const CODE_TEMPLATES = {
  c: {
    'Input Plan': 'scanf("%d", &data);',
    'Output Plan': 'printf("%d", result);',
    'SumAll Plan': 'sum = sum + value;',
    'CountAll Plan': 'count = count + 1;',
    'Loop Plan': 'for(i = 0; i < n; i++) {\n    // loop body\n}',
    'Guard Plan': 'if(condition) {\n    // then branch\n} else {\n    // else branch\n}',
    'Select Smallest Plan': 'if(array[i] < smallest) {\n    smallest = array[i];\n    location = i;\n}',
    'Compare Adjacents Plan': 'if(array[j] > array[j+1]) {\n    // swap needed\n}',
    'Exchange Plan': 'temp = array[a];\narray[a] = array[b];\narray[b] = temp;',
    'LSSE Plan': 'for(i = 0; i < n-1; i++) {\n    // find smallest and exchange\n}',
    'CAE Plan': 'for(j = 0; j < n-i-1; j++) {\n    if(array[j] > array[j+1]) swap();\n}',
    'Error Handler Plan': 'if(divisor == 0) {\n    printf("Error: Division by zero");\n}',
  },
  cpp: {
    'Input Plan': 'cin >> data;',
    'Output Plan': 'cout << result;',
    'SumAll Plan': 'sum = sum + value;',
    'CountAll Plan': 'count = count + 1;',
    'Loop Plan': 'for(int i = 0; i < n; i++) {\n    // loop body\n}',
    'Guard Plan': 'if(condition) {\n    // then branch\n} else {\n    // else branch\n}',
    'Select Smallest Plan': 'if(array[i] < smallest) {\n    smallest = array[i];\n    location = i;\n}',
    'Compare Adjacents Plan': 'if(array[j] > array[j+1]) {\n    // swap needed\n}',
    'Exchange Plan': 'swap(array[a], array[b]);',
    'LSSE Plan': 'for(int i = 0; i < n-1; i++) {\n    // find smallest and exchange\n}',
    'CAE Plan': 'for(int j = 0; j < n-i-1; j++) {\n    if(array[j] > array[j+1]) swap();\n}',
    'Error Handler Plan': 'if(divisor == 0) {\n    cerr << "Error: Division by zero";\n}',
  },
  pascal: {
    'Input Plan': 'readln(data);',
    'Output Plan': 'writeln(result);',
    'SumAll Plan': 'sum := sum + value;',
    'CountAll Plan': 'count := count + 1;',
    'Loop Plan': 'for i := 0 to n-1 do begin\n    // loop body\nend;',
    'Guard Plan': 'if condition then begin\n    // then branch\nend else begin\n    // else branch\nend;',
    'Select Smallest Plan': 'if array[i] < smallest then begin\n    smallest := array[i];\n    location := i;\nend;',
    'Compare Adjacents Plan': 'if array[j] > array[j+1] then begin\n    // swap needed\nend;',
    'Exchange Plan': 'temp := array[a];\narray[a] := array[b];\narray[b] := temp;',
    'LSSE Plan': 'for i := 0 to n-2 do begin\n    // find smallest and exchange\nend;',
    'CAE Plan': 'for j := 0 to n-i-2 do begin\n    if array[j] > array[j+1] then swap();\nend;',
    'Error Handler Plan': 'if divisor = 0 then begin\n    writeln("Error: Division by zero");\nend;',
  },
};